body = 'body'
query_params = 'queryStringParameters'
path_params = 'pathParameters'
http_method = 'httpMethod'
status_code = 'statusCode'
headers = 'headers'
extension = 'extension'
method = 'method'

get = 'GET'
post = 'POST'
patch = 'PATCH'
delete = 'DELETE'
put = 'PUT'

metric = 'metric'
schedule = 'schedule'
recurrence_schedule = 'recurrence_schedule'
tags = 'tags'
target_value = 'target_value'
name = 'name'
value = 'value'
start = 'start'
end = 'end'
offset = 'offset'
limit = 'limit'
note_id = 'note_id'
origin = 'origin'
units = 'units'
completed = 'completed'
priority = 'priority'
time = 'time'
id = 'id'
status = 'status'
success = 'success'
search_text = 'search_text'
not_found = 'not found'
tagged = 'tagged'
occurrence = 'occurrence'
summary = 'summary'
description = 'description'
task = 'task'
url = 'url'
user = 'user'
params_delim = '|'
like = '%'
empty = ''
link = 'link'
id_is_required = 'id is required'
name_is_required = 'name is required'
error = 'error'
text = 'text'
text_is_required = 'text is required'
id_text_or_tags_is_required = 'id, text or tags is required'
image_key = 'image_key'
audio_key = 'audio_key'
metrics = 'metrics'
any_text_is_required = 'text|audio|image is required'
internal_server_error = 'internal server error'

image_described = 'image_described'
audio_transcribed = 'audio_transcribed'
image_text = 'image_text'
image_description = 'image_description'
audio_text = 'audio_text'

minute = 'minute'
hour = 'hour'
day_of_month = 'day_of_month'
month = 'month'
day_of_week = 'day_of_week'

user_id = 'user_id'
metric_id = 'metric_id'
task_id = 'task_id'

sns = 'sns'
s3 = 's3'
transcribe = 'transcribe'
records = 'Records'
object = 'object'
display_summary = 'display_summary'
message = 'Message'
media_file_uri = 'MediaFileUri'
media_format = 'MediaFormat'

file_key = 'file_key'
mp4 = 'mp4'
heic = 'heic'
jpg = 'jpg'
png = 'png'
jpeg = 'jpeg'
m4a = 'm4a'
bucket = 'Bucket'
s3_key = 'Key'
key = 'key'

content_type = 'ContentType'
content= 'content'
s3_body = 'Body'
embedding = 'embedding'
job_name = 'jobName'
results = 'results'
transcripts = 'transcripts'
transcript = 'transcript'
job_id = 'jobId'
bda = 'bedrock-data-automation'
bedrock_runtime = 'bedrock-runtime'

s3_uri = 's3Uri'
request_context='requestContext'
http='http'
utf_8 = 'utf-8'
inference_result = 'inference_result'
request_type = 'RequestType'
create_request_type = 'Create'
update_request_type = 'Update'
secretsmanager = 'secretsmanager'
next_run = 'next_run'
es = 'es'
host = 'host'
port = 'port'
input_text = 'inputText'
application_json = 'application/json'
vector_field = 'vector_field'
settings = 'settings'
knn = 'knn'
refresh_interval= 'refresh_interval'
index = 'index'
properties = 'properties'
type = 'type'
dimension = 'dimension'
mappings = 'mappings'
knn_vector = 'knn_vector'
integer = 'integer'
keyword = 'keyword'
period_seconds = 'period_seconds'
resource_properties = 'ResourceProperties'
cognito_idp = 'cognito-idp'
secret_string = 'SecretString'
cognito_name = 'Name'
cognito_value = 'Value'
cognito_email = 'email'
cognito_email_verified = 'email_verified'
message_action_suppress = 'SUPPRESS'

resource_status = 'Status'
resource_success = 'SUCCESS'
resource_failed = 'FAILED'
resource_reason = 'Reason'


cors_headers = {
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'OPTIONS,GET,POST,PATCH,DELETE'
}
default_region = 'us-east-1'
default_max_tokens = 2048