body = 'body'
query_params = 'queryStringParameters'
path_params = 'pathParameters'
http_method = 'httpMethod'
status_code = 'statusCode'


get = 'GET'
post = 'POST'
patch = 'PATCH'
delete = 'DELETE'



metric = 'metric'
schedule = 'schedule'
recurrence_schedule = 'recurrence_schedule'
tags = 'tags'
target_value = 'target_value'
name  = 'name'
value = 'value'
start = 'start'
end = 'end'
note_id = 'note_id'
origin = 'origin'
units = 'units'
completed = 'completed'
priority = 'priority'
time = 'time'
id = 'id'
status = 'status'
success = 'success'
search_text = 'search_text'
not_found = 'not found'
tagged = 'tagged'
occurrence = 'occurrence'
summary = 'summary'
description = 'description'
task = 'task'
url = 'url'
user = 'user'
params_delim = '|'
like = '%'
empty = ''
link = 'link'
id_is_required = 'id is required'
name_is_required = 'name is required'
error = 'error'