body = 'body'
query_params = 'queryStringParameters'
path_params = 'pathParameters'
http_method = 'httpMethod'
status_code = 'statusCode'

get = 'GET'
post = 'POST'
patch = 'PATCH'
delete = 'DELETE'

metric = 'metric'
schedule = 'schedule'
recurrence_schedule = 'recurrence_schedule'
tags = 'tags'
target_value = 'target_value'
name = 'name'
value = 'value'
start = 'start'
end = 'end'
offset = 'offset'
limit = 'limit'
note_id = 'note_id'
origin = 'origin'
units = 'units'
completed = 'completed'
priority = 'priority'
time = 'time'
id = 'id'
status = 'status'
success = 'success'
search_text = 'search_text'
not_found = 'not found'
tagged = 'tagged'
occurrence = 'occurrence'
summary = 'summary'
description = 'description'
task = 'task'
url = 'url'
user = 'user'
params_delim = '|'
like = '%'
empty = ''
link = 'link'
id_is_required = 'id is required'
name_is_required = 'name is required'
error = 'error'
text = 'text'
text_is_required = 'text is required'
id_text_or_tags_is_required = 'id, text or tags is required'
image_key = 'image_key'
audio_key = 'audio_key'
metrics = 'metrics'
any_text_is_required = 'text|audio|image is required'
internal_server_error = 'internal server error'

image_described = 'image_described'
audio_transcribed = 'audio_transcribed'
image_text = 'image_text'
image_description = 'image_description'
audio_text = 'audio_text'

minute = 'minute'
hour = 'hour'
day_of_month = 'day_of_month'
month = 'month'
day_of_week = 'day_of_week'

user_id='user_id'
metric_id = 'metric_id'
task_id = 'task_id'

sns = 'sns'

display_summary = 'display_summary'